# syntax=docker/dockerfile:1

FROM python:alpine

WORKDIR /app

ARG SOPHOS_ID
ARG SOPHOS_SECRET
ARG ZABBIX_USER
ARG ZABBIX_PASS

ENV SOPHOS_ID=$SOPHOS_ID
ENV SOPHOS_SECRET=$SOPHOS_SECRET
ENV ZABBIX_USER=$ZABBIX_USER
ENV ZABBIX_PASS=$ZABBIX_PASS

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python" ]

CMD ["app.py" ]
